### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by GiggliG** [Epix37/HDT-TwitchPlugin#1]
The front page says this is a twitch plugin for HDT, but leaves out very important information: what exactly does it do?

**Comment by azeier** [comment]
It's a plugin for streamers rather than viewers. HDT logs in to a twitch account you provide and responds to commands in chat (listed in screenshot).

**Comment by azeier** [comment]
Added clarification in readme.

**Comment by GiggliG** [comment]
Ah, I see now. :)
