### ISSUE TITLE
Plugin Fails 2 load

### ISSUE THREAD

**Issue by itSFox** [Epix37/HDT-TwitchPlugin#11]
Again dat problem =(

`11:07:35` PM|Info|ErrorManager.AddError >> New error: Error loading Plugin "TwitchPlugin"
Make sure you are using the latest version of the Plugin and HDT.

System.MissingMethodException: Method not found: 'Hearthstone_Deck_Tracker.Windows.MainWindow Hearthstone_Deck_Tracker.Helper.get_MainWindow()'.
   at TwitchPlugin.TwitchPlugin.Setup()
   at TwitchPlugin.TwitchPlugin.OnLoad()
   at Hearthstone_Deck_Tracker.Plugins.PluginWrapper.Load()
11:07:35 PM|Error|PluginWrapper.Load >> TwitchPlugin:
System.MissingMethodException: Method not found: 'Hearthstone_Deck_Tracker.Windows.MainWindow Hearthstone_Deck_Tracker.Helper.get_MainWindow()'.
   at TwitchPlugin.TwitchPlugin.Setup()
   at TwitchPlugin.TwitchPlugin.OnLoad()
   at Hearthstone_Deck_Tracker.Plugins.PluginWrapper.Load()
11:07:35 PM|Info|PluginWrapper.IsEnabled >> Enabled TwitchPlugin``

**Comment by azeier** [comment]
Loads fine for me on the latest release.

**Comment by itSFox** [comment]
Soz, my bad. I dont know how, but tracker(after update) have OLD plugin version.\
Now all okay, sorry =(
