### ISSUE TITLE
Hearthstats

### ISSUE THREAD

**Issue by HDANILO** [Epix37/HDT-TwitchPlugin#2]
I dont know what plugin is this and I can't find it to download

**Comment by azeier** [comment]
https://github.com/Epix37/HDT-TwitchPlugin/blob/master/README.md

**Comment by HDANILO** [comment]
I've read it, but there says: 

Requirements:

```
Latest version of HDT (v0.10.1)
You are logged in to your HearthStats account in HDT (PLUGINS > HEARTHSTATS)
HDT is synced with HearthStats, AUTO UPLOAD NEW GAMES is enabled
```

I can't find anything about HDT in my interface. I've Searched for it in plugins section, also, searched for a downloadable plugin, didnt find any

**Comment by HDANILO** [comment]
Oh, I was looking into the Option->plugin, not the Plugin button on toolbar
