### ISSUE TITLE
!alldecks

### ISSUE THREAD

**Issue by IlyaHalsky** [Epix37/HDT-TwitchPlugin#3]
http://prntscr.com/7baq6h
Can you make deck separated with line?
Instead of

> OTK: http://hss.io/d/441064, Combo: http://hss.io/d/444204, Pidor Ushastiy: http://hss.io/d/461202, Mech shit: http://hss.io/d/478563, Custom: http://hss.io/d/478656, EU Legend #1 Tempo Mage _UPDATED_: http://hss.io/d/481192, Kripp's agroDragons deck: http://hss.io/d/513246

do

> OTK: http://hss.io/d/441064, 
> Combo: http://hss.io/d/444204, 
> Pidor Ushastiy: http://hss.io/d/461202, 
> Mech shit: http://hss.io/d/478563, 
> Custom: http://hss.io/d/478656, 
> EU Legend #1 Tempo Mage _UPDATED_: http://hss.io/d/481192, 
> Kripp's agroDragons deck: http://hss.io/d/513246

**Comment by azeier** [comment]
IRC does not support linebreaks and has a limit on the number of messages you can sent within a certain timeframe. So turning this into separate messages might be a problem, esp. when combined with other commands.

So the only way would be to somehow clearer separate them, maybe like 

> OTK: http://hss.io/d/441064 | Combo: http://hss.io/d/444204 | Pidor Ushastiy: http://hss.io/d/461202 | Mech shit: http://hss.io/d/478563 | Custom: http://hss.io/d/478656 | EU Legend #1 Tempo Mage UPDATED: http://hss.io/d/481192 | Kripp's agroDragons deck: http://hss.io/d/513246  

or

> [OTK: http://hss.io/d/441064], [Combo: http://hss.io/d/444204], [Pidor Ushastiy: http://hss.io/d/461202], [Mech shit: http://hss.io/d/478563], [Custom: http://hss.io/d/478656], [EU Legend #1 Tempo Mage UPDATED: http://hss.io/d/481192], [Kripp's agroDragons deck: http://hss.io/d/513246]

Another option would be to do this (irc removes spaces):
![1](https://cloud.githubusercontent.com/assets/7737910/7901663/e9930088-0793-11e5-8ce8-a5e4dfe8e030.PNG)
only problem is that it horribly breaks if you have a different chat width
![2](https://cloud.githubusercontent.com/assets/7737910/7901664/ebf8f62a-0793-11e5-81b9-4fad53576e88.PNG)

**Comment by azeier** [comment]
Replacing all spaces in the names seems to work pretty well, what do you think of this?

![3](https://cloud.githubusercontent.com/assets/7737910/7901685/c4ce959a-0794-11e5-84d8-ad46b212d225.PNG)
![4](https://cloud.githubusercontent.com/assets/7737910/7901684/c4cbdcba-0794-11e5-8e14-11cf608364f6.PNG)

**Comment by IlyaHalsky** [comment]
Yea, look great! 1 thing still: Remove

> _

after

> :

So it will be OTK:http://hss.io/d/441064 instead of OTK:_http://hss.io/d/441064,

**Comment by azeier** [comment]
that's how i ended up implementing it for release v0.3, yea.
