### ISSUE TITLE
Hitbox Support?

### ISSUE THREAD

**Issue by ADarkHero** [Epix37/HDT-TwitchPlugin#4]
Hi,
I really like the idea of the Twitch-Plugin, but I'm not using Twitch as a streaming platform myself. If I stream, I choose Hitbox to do so. I wanted to ask, if it's possible to add a feature, to use the Plugin for Hitbox.

Greetings,
ADarkHero

**Comment by azeier** [comment]
After a few minutes of google... it looks like hitbox does not use IRC, making this a bit more complicated. So for now no support, sorry.

**Comment by ADarkHero** [comment]
Okay. Thank you for the quick answer.
