### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by ghost** [Epix37/HDT-TwitchPlugin#5]
Hi,

I followed all the steps but the commands are not working on my chat:

http://gyazo.com/f77ba95a116872c8173916dc058f66fa 

http://gyazo.com/78eae30d911aa2b93f88e1c7fb92d288

What am I doing wrong?

Thanks.

**Comment by alfapatito** [comment]
Cicor could you fix it? I'm having the same problems

**Comment by ghost** [comment]
No, Ive never got a reply about it. :(

**Comment by azeier** [comment]
Turns out, this is because the channel name needs to be all lower case. Fixed with v0.5

**Comment by ghost** [comment]
When I download the Twitch Plugin, I dont find the .dll file.

Where can I find it?

Thanks.

**Comment by azeier** [comment]
https://github.com/Epix37/HDT-TwitchPlugin/releases/tag/v0.5

**Comment by ghost** [comment]
Its working now! Thanks
